name: Hourly Data Fetch

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: node scripts/fetchAllProfiles.js

      - run: |
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add .
          git commit -m "Hourly update" || echo "No changes"
          git push
